package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

type AutoGenerated struct {
	Markets struct {
		Us []struct {
			Stock         string  `json:"stock"`
			Link          string  `json:"link"`
			SerpapiLink   string  `json:"serpapi_link"`
			Name          string  `json:"name"`
			Price         float64 `json:"price"`
			PriceMovement struct {
				Percentage float64 `json:"percentage"`
				Value      float64 `json:"value"`
				Movement   string  `json:"movement"`
			} `json:"price_movement"`
		} `json:"us"`
	} `json:"markets"`
}

func main() {
	content, err := os.ReadFile("./sample2.json")
	if err != nil {
		log.Fatal(err)
	}
	rs := AutoGenerated{}
	if err := json.Unmarshal(content, &rs); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%v\n", rs)
}
